# Generated by Django 5.2 on 2025-07-21 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_documentcategory_filetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
