# Generated by Django 5.2 on 2025-07-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_facultyprofile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultydocument',
            name='file_type',
        ),
    ]
