# Generated by Django 5.2 on 2025-07-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_academicyear_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydocument',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_documents', to='faculty.semester'),
        ),
    ]
