# Generated by Django 5.2 on 2025-07-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_facultydocument_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('document_categories', models.ManyToManyField(related_name='included_in_templates', to='faculty.documentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='faculty.documentcategory')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='faculty.semester')),
            ],
            options={
                'unique_together': {('semester', 'document_category')},
            },
        ),
    ]
