# Generated by Django 5.2 on 2025-08-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_deliverabletemplate_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydocument',
            name='deliverable',
            field=models.ForeignKey(blank=True, help_text='If this document fulfills a specific deliverable, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='faculty.deliverable'),
        ),
    ]
