# Generated by Django 5.2 on 2025-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_facultydocument_deliverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
