# Generated by Django 5.2 on 2025-11-02 02:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_teachingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydocument',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
