# Generated by Django 5.2 on 2025-11-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_facultydocument_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
