# Generated by Django 5.2 on 2025-12-01 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_teachingassignment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydocument',
            name='teaching_assignment',
            field=models.ForeignKey(blank=True, help_text='If this document is for a specific teaching assignment, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='faculty.teachingassignment'),
        ),
    ]
