# Generated by Django 5.2 on 2026-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_facultydocument_teaching_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='faculty_code',
            field=models.CharField(blank=True, help_text='Unique faculty code, e.g. FA0018SP2023', max_length=20, null=True, unique=True),
        ),
    ]
