# Generated by Django 5.2 on 2026-02-01 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_facultyprofile_faculty_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, apostrophes, periods, and hyphens.', regex="^[A-Za-zÀ-ÿÑñ\\s\\.\\-']+$")]),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, apostrophes, periods, and hyphens.', regex="^[A-Za-zÀ-ÿÑñ\\s\\.\\-']+$")]),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, apostrophes, periods, and hyphens.', regex="^[A-Za-zÀ-ÿÑñ\\s\\.\\-']+$")]),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g., Jr., Sr., III (optional)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, apostrophes, periods, and hyphens.', regex="^[A-Za-zÀ-ÿÑñ\\s\\.\\-']+$")]),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g., 09171234567).', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Names may only contain letters, spaces, apostrophes, periods, and hyphens.', regex="^[A-Za-zÀ-ÿÑñ\\s\\.\\-']+$")]),
        ),
    ]
