# Generated by Django 5.2 on 2026-02-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_facultyprofile_first_name_facultyprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
