# Generated by GitHub Copilot on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0019_facultydocument_archive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverabletemplate",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
