# Generated by Django 6.0.4 on 2026-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_faculty_position_designation_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Optional administrative title used in exports (e.g. Program Chair, Campus Director).', max_length=255),
        ),
    ]
