"""
Django settings for FEMS project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os
from celery.schedules import crontab
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)
#Read the .env file
environ.Env.read_env(BASE_DIR / '.env')  

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')



ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=["http://localhost:8000"])
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)

# Only send cookies over HTTPS
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'channels',
    'base.apps.BaseConfig',
    'adminhub.apps.AdminhubConfig',
    'faculty.apps.FacultyConfig',
    'applicant.apps.ApplicantConfig',
    'rfid.apps.RfidConfig',
    'notifications.apps.NotificationsConfig',
    # django-unfold: modern admin theme. Must precede django.contrib.admin so
    # its template/static overrides take effect. Themes only the Django contrib
    # admin at /system-config/ (see UNFOLD dict below); the custom staff
    # dashboard in templates/admin/admin_*.html is unaffected.
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'FEMS.middleware.twofa.TwoFAMiddleware', 
    'FEMS.middleware.cachecontrol.AuthSensitiveCacheControlMiddleware',  
]

ROOT_URLCONF = 'FEMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'FEMS.wsgi.application'
ASGI_APPLICATION = 'FEMS.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Uses Custom User Model instead of default user
AUTH_USER_MODEL = 'base.Account'  

# Login URL
LOGIN_URL = 'login'

# Redirect URL after logout
LOGOUT_REDIRECT_URL = 'login'  


# Email backend for sending emails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Default: Gmail SMTP settings
EMAIL_HOST = "smtp-relay.brevo.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")             # <-- Replace with Gmail address
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")        # <-- Use an App Password for Gmail (not your regular password)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
BREVO_API_KEY = env("BREVO_API_KEY")
SUPPORT_EMAIL = env("SUPPORT_EMAIL", default=DEFAULT_FROM_EMAIL)
SITE_BASE_URL = env("SITE_BASE_URL")

# Google Service Account Credentials
# Google Service Account Credentials
GOOGLE_SERVICE_ACCOUNT_FILE = env("GOOGLE_SERVICE_ACCOUNT_FILE")  

# Google OAuth2 Client Secret
GOOGLE_CLIENT_SECRET_FILE = env("GOOGLE_CLIENT_SECRET_FILE")

# Google OAuth2 Redirect URI
GOOGLE_OAUTH2_REDIRECT_URI = env("GOOGLE_OAUTH2_REDIRECT_URI")

# --------- NEW: support JSON from env on platforms like Railway ---------
GOOGLE_CLIENT_SECRET_JSON_B64 = os.getenv("GOOGLE_CLIENT_SECRET_JSON_B64")
GOOGLE_SERVICE_ACCOUNT_JSON_B64 = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON_B64")

if GOOGLE_CLIENT_SECRET_JSON_B64:
    import base64
    Path(GOOGLE_CLIENT_SECRET_FILE).parent.mkdir(parents=True, exist_ok=True)
    with open(GOOGLE_CLIENT_SECRET_FILE, "wb") as f:
        f.write(base64.b64decode(GOOGLE_CLIENT_SECRET_JSON_B64))

if GOOGLE_SERVICE_ACCOUNT_JSON_B64:
    import base64
    Path(GOOGLE_SERVICE_ACCOUNT_FILE).parent.mkdir(parents=True, exist_ok=True)
    with open(GOOGLE_SERVICE_ACCOUNT_FILE, "wb") as f:
        f.write(base64.b64decode(GOOGLE_SERVICE_ACCOUNT_JSON_B64))
# ------------------------------------------------------------------------

# Fernet Key for encryption
FERNET_KEY = env("FERNET_KEY")

GOOGLE_DRIVE_ROOT_FOLDER_ID = env("GOOGLE_DRIVE_ROOT_FOLDER_ID")




CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

CHANNEL_REDIS_URL = env("CHANNEL_REDIS_URL", default=CELERY_BROKER_URL)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
        },
    },
}

NOTIFICATION_RETENTION_DAYS = env.int("NOTIFICATION_RETENTION_DAYS", default=60)
NOTIFICATION_MAX_READ_PER_USER = env.int("NOTIFICATION_MAX_READ_PER_USER", default=20)

CELERY_BEAT_SCHEDULE = {
    "sync-active-academic-calendar-daily": {
        "task": "adminhub.tasks.sync_active_academic_calendar_task",
        "schedule": crontab(minute=5, hour=0),
    },
    "publish-due-scheduled-announcements": {
        "task": "adminhub.tasks.publish_due_scheduled_announcements_task",
        "schedule": crontab(minute="*/2"),
    },
    "cleanup-notifications-daily": {
        "task": "notifications.tasks.cleanup_notifications_task",
        "schedule": crontab(minute=10, hour=1),
    },
    "cleanup-user-otps-daily": {
        "task": "base.tasks.cleanup_user_otps_task",
        "schedule": crontab(minute=15, hour=1),
    },
    "deliverable-deadline-reminders-daily": {
        "task": "notifications.tasks.send_deliverable_deadline_reminders_task",
        "schedule": crontab(minute=20, hour=7),
    },
    "notify-missing-deliverables-daily": {
        "task": "notifications.tasks.notify_missing_deliverables_task",
        "schedule": crontab(minute=30, hour=7),
    },
}


# ---------------------------------------------------------------------------
# django-unfold admin theme
# ---------------------------------------------------------------------------
# Themes the Django contrib admin at /system-config/ with PUP-GURONEx (FEMS)
# branding. All branding lives here (not in forked templates) so it survives
# Django/Unfold upgrades. The maroon scale below is anchored on the three brand
# tokens used across the app: #a80707 (600), #800505 (700), #4a0101 (900).
UNFOLD = {
    "SITE_TITLE": "PUP-GURONEx System Config",
    "SITE_HEADER": "PUP-GURONEx",
    "SITE_SUBHEADER": _("System Configuration"),
    "SITE_URL": "/",
    "SITE_LOGO": lambda request: static("images/pup-logo.png"),
    "SITE_ICON": lambda request: static("images/pup-logo.png"),
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "href": lambda request: static("images/pup-favicon.ico"),
            "type": "image/x-icon",
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "DASHBOARD_CALLBACK": "FEMS.admin_dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "253 242 242",
            "100": "251 224 224",
            "200": "245 194 194",
            "300": "236 154 154",
            "400": "221 95 95",
            "500": "197 48 48",
            "600": "168 7 7",    # #a80707 — brand gradient mid
            "700": "128 5 5",    # #800505 — brand primary maroon
            "800": "106 4 4",
            "900": "74 1 1",     # #4a0101 — brand dark
            "950": "46 0 0",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Overview"),
                "separator": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Accounts & Access"),
                "separator": True,
                "items": [
                    {
                        "title": _("Accounts"),
                        "icon": "group",
                        "link": reverse_lazy("admin:base_account_changelist"),
                    },
                    {
                        "title": _("Google Storage"),
                        "icon": "cloud",
                        "link": reverse_lazy("admin:base_googlestorageaccount_changelist"),
                    },
                ],
            },
            {
                "title": _("Faculty"),
                "separator": True,
                "items": [
                    {
                        "title": _("Faculty Profiles"),
                        "icon": "school",
                        "link": reverse_lazy("admin:faculty_facultyprofile_changelist"),
                    },
                    {
                        "title": _("Documents"),
                        "icon": "description",
                        "link": reverse_lazy("admin:faculty_facultydocument_changelist"),
                    },
                    {
                        "title": _("Requests"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:faculty_facultyrequest_changelist"),
                    },
                    {
                        "title": _("Clearance Requests"),
                        "icon": "verified",
                        "link": reverse_lazy("admin:faculty_facultyclearancerequest_changelist"),
                    },
                    {
                        "title": _("Deliverables"),
                        "icon": "task",
                        "link": reverse_lazy("admin:faculty_deliverable_changelist"),
                    },
                ],
            },
            {
                "title": _("Applicants"),
                "separator": True,
                "items": [
                    {
                        "title": _("Applicants"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy("admin:applicant_applicant_changelist"),
                    },
                    {
                        "title": _("Evaluation Criteria"),
                        "icon": "checklist",
                        "link": reverse_lazy("admin:applicant_evaluationcriteria_changelist"),
                    },
                    {
                        "title": _("Areas of Specialization"),
                        "icon": "category",
                        "link": reverse_lazy("admin:applicant_areaofspecialization_changelist"),
                    },
                ],
            },
            {
                "title": _("Attendance & RFID"),
                "separator": True,
                "items": [
                    {
                        "title": _("RFID Tags"),
                        "icon": "nfc",
                        "link": reverse_lazy("admin:rfid_rfidtag_changelist"),
                    },
                    {
                        "title": _("Attendance Logs"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:rfid_attendancelog_changelist"),
                    },
                    {
                        "title": _("ESP32 Devices"),
                        "icon": "sensors",
                        "link": reverse_lazy("admin:rfid_esp32wifi_changelist"),
                    },
                ],
            },
            {
                "title": _("Announcements & Content"),
                "separator": True,
                "items": [
                    {
                        "title": _("Announcements"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:adminhub_announcement_changelist"),
                    },
                    {
                        "title": _("Document Templates"),
                        "icon": "file_copy",
                        "link": reverse_lazy("admin:adminhub_documenttemplate_changelist"),
                    },
                    {
                        "title": _("PUP Sites"),
                        "icon": "apartment",
                        "link": reverse_lazy("admin:adminhub_pupsite_changelist"),
                    },
                ],
            },
            {
                "title": _("System & Logs"),
                "separator": True,
                "items": [
                    {
                        "title": _("Notifications"),
                        "icon": "notifications",
                        "link": reverse_lazy("admin:notifications_notification_changelist"),
                    },
                    {
                        "title": _("Activity Log"),
                        "icon": "history",
                        "link": reverse_lazy("admin:notifications_activitylog_changelist"),
                    },
                    {
                        "title": _("Created Account Log"),
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:adminhub_createdaccountlog_changelist"),
                    },
                ],
            },
        ],
    },
}
