# Generated by Django 5.2 on 2025-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32WiFi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='ESP32', max_length=50)),
                ('reset_wifi', models.BooleanField(default=False)),
            ],
        ),
    ]
