# Generated by Django 5.2 on 2025-08-28 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_esp32wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
