# Generated by Django 5.2 on 2025-11-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_alter_attendancelog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
