# Generated by Django 5.2 on 2025-11-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_teachingassignment_room'),
        ('rfid', '0004_rfidtag_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='teaching_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.teachingassignment'),
        ),
    ]
