# Generated by Django 5.2 on 2025-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_teachingassignment_room'),
        ('rfid', '0005_attendancelog_teaching_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancelog',
            name='teaching_assignment',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='uid',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='teaching_assignments',
            field=models.ManyToManyField(blank=True, related_name='attendance_logs', to='faculty.teachingassignment'),
        ),
    ]
