# Generated by Django 5.2 on 2025-11-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0006_remove_attendancelog_teaching_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
