# Generated by Django 5.2 on 2025-11-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0007_attendancelog_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
