# Generated by Django 6.0.4 on 2026-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0008_attendancelog_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='documentation_drive_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Google Drive link to the uploaded photo documentation.', max_length=500),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='manual_reason',
            field=models.CharField(blank=True, choices=[('rfid_offline', 'RFID Reader Offline / Malfunction'), ('card_unavailable', 'RFID Card Lost or Unavailable'), ('online_class', 'Online Class'), ('offsite_activity', 'Official Business / Off-campus Activity'), ('network_issue', 'Device or Network Issue'), ('other', 'Other')], help_text='Why this attendance was logged manually instead of via RFID.', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='manual_reason_details',
            field=models.TextField(blank=True, help_text="Required explanation when the reason is 'Other'."),
        ),
    ]
