# Generated by Django 5.2 on 2025-08-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0002_announcement_announcementviewlog'),
        ('applicant', '0002_applicant_account_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedAccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.applicant')),
            ],
        ),
    ]
