# Generated by Django 5.2 on 2025-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0003_createdaccountlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdaccountlog',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='createdaccountlog',
            name='applicant_id_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='createdaccountlog',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
