# Generated by Django 5.2 on 2025-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0004_createdaccountlog_applicant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUPSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
