# Generated by Django 5.2 on 2025-12-03 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0005_pupsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupsite',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
