# Generated by Django 6.0.4 on 2026-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhub', '0014_adminprofile_position_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Optional administrative title used in exports (e.g. HR Coordinator, Guidance Coordinator).', max_length=255),
        ),
    ]
