# Generated by Django 5.2 on 2025-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='two_factor_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
