# Generated by Django 5.2 on 2025-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_googledrivetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleStorageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Primary', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('_access_token', models.TextField()),
                ('_refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
