# Generated by Django 5.2 on 2025-08-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_googlestorageaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleDriveToken',
        ),
    ]
