# Generated by Django 5.2 on 2025-10-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_googledrivetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
