# Generated by Django 5.2 on 2025-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_userotp_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_background_image', models.BooleanField(default=True)),
                ('overlay_style', models.CharField(choices=[('none', 'None (no overlay)'), ('dark', 'Dark overlay (muted image)'), ('silhouette', 'Silhouette (grayscale + darkened)')], default='dark', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Appearance',
                'verbose_name_plural': 'Landing Appearance',
            },
        ),
    ]
