# Generated by Django 5.2 on 2026-04-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='notificatio_action_4a6b01_idx'), models.Index(fields=['actor', 'created_at'], name='notificatio_actor_i_9a6dbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('faculty_approval_request', 'Faculty Approval Request'), ('faculty_account_approved', 'Faculty Account Approved'), ('faculty_account_rejected', 'Faculty Account Rejected'), ('faculty_document_uploaded', 'Faculty Document Uploaded'), ('faculty_deliverable_uploaded', 'Faculty Deliverable Uploaded'), ('document_status_updated', 'Document Status Updated'), ('announcement_published', 'Announcement Published'), ('applicant_submitted', 'Applicant Submitted'), ('teaching_assignment_assigned', 'Teaching Assignment Assigned'), ('google_storage_changed', 'Google Storage Changed'), ('deliverable_deadline_reminder', 'Deliverable Deadline Reminder'), ('missing_deliverables', 'Missing Deliverables'), ('system', 'System')], default='system', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=512)),
                ('related_type', models.CharField(blank=True, max_length=100)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_important', models.BooleanField(db_index=True, default=False)),
                ('aggregate_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('aggregate_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient', 'aggregate_key', 'is_read'], name='notificatio_recipie_063c52_idx')],
            },
        ),
    ]
