# Generated by Django 6.0.4 on 2026-06-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('faculty_approval_request', 'Faculty Approval Request'), ('faculty_account_approved', 'Faculty Account Approved'), ('faculty_account_rejected', 'Faculty Account Rejected'), ('faculty_document_uploaded', 'Faculty Document Uploaded'), ('faculty_deliverable_uploaded', 'Faculty Deliverable Uploaded'), ('document_status_updated', 'Document Status Updated'), ('announcement_published', 'Announcement Published'), ('applicant_submitted', 'Applicant Submitted'), ('teaching_assignment_assigned', 'Teaching Assignment Assigned'), ('google_storage_changed', 'Google Storage Changed'), ('deliverable_deadline_reminder', 'Deliverable Deadline Reminder'), ('missing_deliverables', 'Missing Deliverables'), ('applicant_reschedule_requested', 'Applicant Reschedule Requested'), ('applicant_step_document_uploaded', 'Applicant Step Document Uploaded'), ('applicant_availability_confirmed', 'Applicant Availability Confirmed'), ('applicant_application_withdrawn', 'Applicant Application Withdrawn'), ('evaluation_submitted', 'Evaluation Submitted'), ('system', 'System')], default='system', max_length=64),
        ),
    ]
