# Generated by Django 5.2 on 2025-08-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='account_created',
            field=models.BooleanField(default=False),
        ),
    ]
