# Generated by Django 5.2 on 2025-08-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_applicant_account_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='contact',
            new_name='contact_number',
        ),
    ]
