# Generated by Django 5.2 on 2025-08-28 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_rename_contact_applicant_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
