# Generated by Django 5.2 on 2025-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_applicant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='college_course',
            field=models.CharField(blank=True, help_text='e.g. BS Computer Science', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='college_graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 2022', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='college_school_name',
            field=models.CharField(blank=True, help_text='e.g. University of X', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grad_course',
            field=models.CharField(blank=True, help_text='e.g. MS Education (leave blank if not applicable)', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grad_graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 2024', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grad_school_name',
            field=models.CharField(blank=True, help_text='e.g. University of Y', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
