# Generated by Django 5.2 on 2026-01-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicant_college_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='college_course',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='college_graduation_year',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='college_school_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='grad_course',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='grad_graduation_year',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='grad_school_name',
        ),
    ]
