# Generated by Django 5.2 on 2026-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_remove_applicant_college_course_and_more'),
        ('faculty', '0015_facultydocument_teaching_assignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicantrequireddocument',
            constraint=models.UniqueConstraint(fields=('document_category',), name='unique_required_doc_per_category'),
        ),
    ]
