# Generated by Django 5.2 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_applicantrequireddocument_unique_required_doc_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='demo_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='failed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='for_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='psych_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
