# Generated by Django 6.0.4 on 2026-06-08 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_evaluationassignment_evaluator_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g., 09171234567).', regex='^09\\d{9}$')]),
        ),
    ]
