# Generated by Django 6.0.4 on 2026-06-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0019_demo_time_location_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
