# Generated by Django 6.0.4 on 2026-07-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0020_applicant_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='current_employment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='eligibility',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_currently_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantstepdocument',
            name='step_type',
            field=models.CharField(choices=[('psych_test', 'Psych Test'), ('permit_to_teach', 'Permit to Teach'), ('contract_admin', 'Contract (Admin Uploaded)'), ('contract_signed', 'Signed Contract (Applicant)'), ('salary_requirement', 'First Salary Requirement')], max_length=30),
        ),
    ]
